### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by qdequele** [codebender828/breadstick#2]
**Describe the bug**
It seems that the `window` is not defined.
For now, I can't make it work. No matter how I try to use the library.

**To Reproduce**
`yarn install breadstick`

Add to one of your component :
```javascript
import Breadstick from 'breadstick'
const breadstick = new Breadstick()
```

**Expected behavior**
Allowed to use the library

**Screenshots**
<img width="1920" alt="Capture d’écran 2019-12-05 à 17 42 17" src="https://user-images.githubusercontent.com/6064892/70260348-5d85ca00-1790-11ea-9aa4-a77d9884e8a6.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15
- Browser: Safari 13.0.2 & Firefox 72.0a1 

**Additional context**
- Nuxt: 2.0.0

PS: Your notification system is the first one I found that is not naturally ugly. Thanks for your work.

**Comment by codebender828** [comment]
Hey @qdequele Thanks for mentioning this! Also thanks for trying it out. I hadn't yet made to work with  SSR out of the box with nuxt. It's on the roadmap, though. Will look into this and fix it as soon as possible.

**Comment by codebender828** [comment]
For now a workaround for nuxt would be to use it in SPA mode if it's not too big of an issue. Thanks for the headsup.

**Comment by codebender828** [comment]
Hello @qdequele ! SSR support has been added to breadstick in #4 . I also published an update the [docs](https://github.com/codebender828/breadstick), so you might need to make a few tweeks. Good luck and closing this for now :)

**Comment by codebender828** [comment]
Also, consider looking at the nuxt starter. I noticed your project uses nuxt. Here you go.
http://bit.ly/breadstick-nuxt
