### ISSUE TITLE
Cannot call a class as a function

### ISSUE THREAD

**Issue by DominusKelvin** [codebender828/breadstick#3]
**Describe the bug**
Uncaught TypeError: Cannot call a class as a function

**To Reproduce**
`yarn add breadstick`
1. In plugins/ create a plugin **breadstick.client.js** and add
   `import Vue from 'vue'
     import Breadstick from 'breadstick'
     Vue.use(Breadstick)
`
2. Then add the breadstick plugin to the plugins array in `nuxt.config.js`

**Expected behavior**
There shouldn't be any error logs on the console.

**Screenshots**
![Screenshot 2019-12-13 at 18 36 55](https://user-images.githubusercontent.com/24433274/70820146-3c4c5b80-1dd8-11ea-8689-7fe906d67e81.png)

**Desktop (please complete the following information):**
 - OS: mac OS
 - Browser: Chrome
 - Version 78.0.3904.108 (Official Build) (64-bit)

**Additional context**
**Using Nuxt v2.10.2**

**Really want to see breadstick in action**

**Comment by codebender828** [comment]
Hey @DominusKelvin ! Thanks for the heads up on this. I think you might be calling the default export class from breadstick as a function.

**Comment by codebender828** [comment]
Fixed in #4
